KDHOCKEYAPP_LIBRARY_FILENAME = $$shadowed($$PWD/$${QMAKE_PREFIX_STATICLIB}KDHockeyApp.$${QMAKE_EXTENSION_STATICLIB})

INCLUDEPATH += $$PWD
LIBS += $$KDHOCKEYAPP_LIBRARY_FILENAME
PRE_TARGETDEPS += $$KDHOCKEYAPP_LIBRARY_FILENAME
QT += network qml

android: QT += androidextras

include(../3rdparty/breakpad/breakpad.pri)
